;;; gyach-faces.el --- face definitions for ElGyach

;; Copyright (C) 2003  Free Software Foundation, Inc.

;; Author: Matthew Kennedy <mbkennedy@austin.rr.com>
;; Keywords: convenience

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
;; Boston, MA 02111-1307, USA.

;;; Commentary:

;; Inspired by the default face settings in ERC

;;; Code:

(defgroup gyach-faces nil
  "Faces for ERC."
  :group 'gyach)

(defface gyach-default-face '((t))
  "ElGyach default face."
  :group 'gyach-faces)

(defface gyach-event-face '((t (:bold t :foreground "SlateBlue")))
  "ElGyach event face.
`gyach-event-face' defines the face to use for enter/leave messages etc."
  :group 'gyach-faces)

(defface gyach-action-face '((t (:bold t)))
  "ElGyach face for actions generated by /me or the : prefix."
  :group 'gyach-faces)

(defface gyach-username-face '((t (:bold t)))
  "Gyach username face."
  :group 'gyach-faces)

(defface gyach-input-face '((t (:foreground "brown")))
  "Gyach face used for your input."
  :group 'gyach-faces)

(defface gyach-input-username-face '((t (:bold t :foreground "brown")))
  "Gyach face used for rendering usersname in your input."
  :group 'gyach-faces)

(provide 'gyach-faces)

;;; gyach-faces.el ends here
